[build]
  command = "npm run build -- --configuration production"
  publish = "dist/ventify2-front/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build -- --configuration production"
  publish = "dist/ventify2-front/browser"

[context.deploy-preview]
  command = "npm run build -- --configuration production"
  publish = "dist/ventify2-front/browser"

[context.branch-deploy]
  command = "npm run build -- --configuration production"
  publish = "dist/ventify2-front/browser"
